---
# Source: mysql/templates/pv.yaml
apiVersion: v1
kind: "PersistentVolume"
metadata:
  name: mysql-volume
  labels:
    app: mysql
    group: web
spec:
  capacity:
    storage: "10Gi" 
  accessModes:
    - "ReadWriteOnce"
  persistentVolumeReclaimPolicy: Recycle
  claimRef:
    namespace: egov
    name: mysql-volume
  awsElasticBlockStore:
    volumeID: vol-0d860de150830abad
    fsType: ext4
---
# Source: mysql/templates/pvc.yaml
apiVersion: "v1"
kind: PersistentVolumeClaim
metadata:
  name: mysql-volume
  namespace: egov
  labels:
    app: mysql
    group: web
spec:
  accessModes:
   - "ReadWriteOnce"
  resources:
    requests:
        storage: "10Gi"
  storageClassName: "default"
  volumeMode: "Filesystem"
  volumeName: mysql-volume
---
# Source: mysql/templates/service.yaml
# service.yaml---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: egov  
  annotations: 
  labels:
    app: mysql      
    group: web   
spec:
  selector:
    app: mysql      
    group: web    
  ports:
  - port: 3306
    targetPort: 3306
---
# Source: mysql/templates/deployment.yaml
# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: egov
  labels:
    app: mysql      
    group: web   
spec:
  selector:
    matchLabels:
      app: mysql      
      group: web
  strategy:
    rollingUpdate:
      maxUnavailable: 0     
  replicas: 1
  template:
    metadata:  
      annotations:
        deployment-timestamp: "20200611172005"    
      labels:
        app: mysql      
        group: web            
    spec:     
      volumes:
        - name: mysql-volume
          persistentVolumeClaim:
            claimName: mysql-volume 
        
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              topologyKey: "failure-domain.beta.kubernetes.io/zone"
              labelSelector:
                matchLabels:
                  app: mysql      
                  group: web     
      initContainers:
        - name: "remove-lost-found"
          image: "busybox:1.31.1"
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: 10Mi
              cpu: 10m
          command:  ["rm", "-fr", "/var/lib/mysql/lost+found"]
                    
      containers:      
        - name: mysql
          image: egovio/mysql:%!s(float64=5.7)
          imagePullPolicy: IfNotPresent             
          ports:
            - name: http
              containerPort: 3306
              protocol: TCP              
          readinessProbe:
            exec:
              command:
              - sh
              - -c
              - "mysqladmin ping -u root -p${MYSQL_ROOT_PASSWORD}"
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 60
            successThreshold: 1
            failureThreshold: 5     
             
          livenessProbe:
            exec:
              command:
              - sh
              - -c
              - "mysqladmin ping -u root -p${MYSQL_ROOT_PASSWORD}"
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 60
            successThreshold: 1
            failureThreshold: 5 
            
          lifecycle:
            preStop:
              exec:
                command:
                - sh
                - -c
                - sleep 10
          volumeMounts:
            - name: mysql-volume
              mountPath: /var/lib/mysql
                                     
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: mysql-password
            - name: MYSQL_USER
              value: ""
            - name: MYSQL_DATABASE
              value: ""      
                                                 
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
